#!/usr/bin/env python
from sklearn import linear_model

all_refs = [x.split('\n')[0] for x in open("pro.out")]

score_diffs = []
x_vectors = []

for i in all_refs:
  (x, g) = i.split(';')
  temporary_x = []
  for x in x[1:-1].split(', '):
    temporary_x.append(x)
  score_diffs.append(float(g))
  x_vectors.append(temporary_x)

clf = linear_model.LinearRegression()
clf.fit(x_vectors, score_diffs)
coefs = clf.coef_

print coefs

# rather than binary, use magnitude
#
